---
- name: Include variable with package names
  include_vars:
    file: vars/deps.yml
  tags: yum  

- name: Install Ruby app deps via yum
  become: yes
  ansible.builtin.yum:
    state: latest
    update_cache: yes
    name: "{{ packages }}"
  tags: yum
      
- name: Create ruby-app folder
  become: yes
  ansible.builtin.file:
    path: ~/apps/ruby-app
    state: directory
    owner: vagrant
    group: vagrant
    mode: 0777
  tags: git

- name: Clone Slurm repo
  ansible.builtin.git:
    repo: "https://{{ gitlabuser | urlencode }}:{{ gitlabpassword | urlencode }}@gitlab.slurm.io/edu/xpaste_practicum.git"
    dest: /home/vagrant/apps/ruby-app
  notify: Restart ruby-app service
  tags: git

- name: Include bundle task list
  ansible.builtin.include_tasks: bundle.yml
  
- name: Change the httpd_t domain to permissive
  become: yes
  community.general.selinux_permissive:
    name: httpd_t
    permissive: true
  tags: selinux

- name: Modify /run permissions
  become: true
  ansible.builtin.shell:
    chmod 777 /run

- name: Copy systemd service file
  become: yes
  ansible.builtin.template:
    src: templates/ruby-app.service.j2
    dest: /etc/systemd/system/ruby-app.service
    owner: root
    group: root
    mode: 0644
  notify: Restart ruby-app service
  tags: systemd
  