---
- name: Install nginx
  ansible.builtin.yum:
    state: latest
    update_cache: yes
    name:     
      - nginx

- name: Copy nginx config
  ansible.builtin.copy:
    src: files/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644

- name: Restart nginx with new config
  ansible.builtin.service:
    name: nginx
    state: restarted