---
- name: Install nginx
  ansible.builtin.yum:
    state: latest
    update_cache: yes
    name:     
      - nginx

- name: Copy nginx config
  ansible.builtin.copy:
    src: files/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart nginx
  tags: nginx
