##################################################
# Ruby app on CentOS
##################################################
---
- name: Ruby app server
  hosts: centos
  vars_files:
    - passwd.yml
    - vars/main.yml
  
  roles:
    - role: zzet.rbenv
      vars:
        rbenv:
          env: user
          version: v1.0.0
          default_ruby: 2.6.10
          rubies:
            - version: 2.6.10
      rbenv_users:
        - vagrant
      tags: rbenv
    - role: postgresql
      become: yes
      tags: postgresql
    - role: ruby-app
      tags: ruby
    - role: nginx
      become: yes
      tags: nginx

